name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'website/**'
      - 'translations/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'website/**'
      - 'translations/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: pnpm i
      - run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    #     node-version: [12.x, 14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: pnpm i
      - run: pnpm test

  publish:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'brendonovich/simple-obs'
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Set package versions
        if: github.ref == 'refs/heads/main'
        run: pnpm set-package-versions
        env:
          RELEASE_COMMIT_SHA: ${{ github.sha }}
      - name: Publish to npm
        if: github.ref == 'refs/heads/main' || github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        run: pnpm publish -r --tag ${TAG}
        env:
          TAG: ${{ github.ref == 'refs/heads/main' && '--tag=main' || ((contains(github.ref_name, '-rc.') && '--tag=dev') || '' )}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
