name: CI

on:
  push:
    branches: [wsv5]
  pull_request:
    branches: [wsv5]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    #     node-version: [12.x, 14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - run: pnpm test
